### ISSUE TITLE
Crashing at "inverse stft of instruments and vocals"

### ISSUE THREAD

**Issue by ManOrMonster** [Anjok07/ultimatevocalremovergui#19]
Using GPU or CPU, it gets to "inverse stft of instruments and vocals", hangs for about 30 seconds, then closes. This is on v2 and v4. I tried with the latest version of tsurumeso's command line vocal remover and it works fine.

I'm using a GTX 1080ti, 32GB of system RAM, Windows 10. I tried with a clean install of both Python 3.8 and 3.7.

The console output:
`100%|██████████████████████████████████████████████████████████████████████████████████| 42/42 [00:03<00:00, 11.34it/s]
`

Installed packages:

audioread==2.1.9
cffi==1.14.3
dataclasses==0.6
decorator==4.4.2
future==0.18.2
joblib==0.17.0
librosa==0.6.3
llvmlite==0.31.0
numba==0.48.0
numpy==1.19.4
opencv-python==4.4.0.46
Pillow==8.0.1
pycparser==2.20
resampy==0.2.2
scikit-learn==0.23.2
scipy==1.5.4
six==1.15.0
SoundFile==0.10.3.post1
soundstretch==1.2
threadpoolctl==2.1.0
torch==1.7.0+cu110
torchaudio==0.7.0
torchvision==0.8.1+cu110
tqdm==4.30.0
typing-extensions==3.7.4.3

**Comment by DilanBoskan** [comment]
Could you try the latest version in the beta branch and see if this issue still persists?

**Comment by ManOrMonster** [comment]
When I ran, I got:
```
File "E:\ultimatevocalremovergui BETA\VocalRemover.py", line 7, in <module>
    from tkinterdnd2 import TkinterDnD, DND_FILES  # Enable Drag & Drop
ModuleNotFoundError: No module named 'tkinterdnd2'
```
Tkinterdnd2  is not in your requirements.txt file. I had to manually install it [from here](https://github.com/pmgagne/tkinterdnd2).

I'm able to run it after that, but there are some issues. For one, when I select my audio file, it puts the path in braces and I'm unable to remove them since the path is grayed out in the UI. 

![image](https://user-images.githubusercontent.com/3925151/98591808-ffaa0e00-228d-11eb-8c74-3cdc4f697c9f.png)

When I try to convert, I get this error:

![image](https://user-images.githubusercontent.com/3925151/98591715-ddb08b80-228d-11eb-8e04-db68ba3fee56.png)

Also, I put your v2 stacked models in the v2/Stacked Models folder, but "Choose Stacked Model" is still grayed out, so I can't try to use v2 at all. I don't know where to find models with the new naming convention, so I'm using the ones from your previous releases (v2 from github and v4 from discord). The v2 ones are named like "Multi-Genre Model.pth".

**Comment by DilanBoskan** [comment]
Check the latest beta commit, it should fix this issue

**Comment by Anjok07** [comment]
@ManOrMonster The 'Multi-Genre Model' is an instrumental model. I'm going to rename them in the main release in a few days. However, those model were trained on the default values so they should run exactly as intended without being renamed.

**Comment by Anjok07** [comment]
@DilanBoskan I'm thinking maybe we should change the v2 and v4 folders' naming convention from 'Instrumental Models' to 'Main Models'. At least for now until I get the vocal models trained up.

**Comment by ManOrMonster** [comment]
I'm still getting the issue with curly braces in the file path:

![image](https://user-images.githubusercontent.com/3925151/98599482-3d606400-2299-11eb-8361-a30ba49fa8c2.png)

**Comment by DilanBoskan** [comment]
This is not an issue, but rather a visual bug, it should not affect anything

**Comment by ManOrMonster** [comment]
Well this must be unrelated then, because when I try to convert, I get this:

![image](https://user-images.githubusercontent.com/3925151/98600441-cb891a00-229a-11eb-8ec2-15d0247b1147.png)

**Comment by DilanBoskan** [comment]
Fixed bug

**Comment by ManOrMonster** [comment]
I'm able to get to the same point as before now, and it still locks up at "inverse stft of instruments and vocals". So this is not fixed.

**Comment by DilanBoskan** [comment]
@Anjok07 Can you check if it still works for you in the latest commit?

**Comment by DilanBoskan** [comment]
For him it was resolved, very confusing

**Comment by DilanBoskan** [comment]
Can yo ureplace the VocalRemover.py in your file with this one, and show me the console output?
Thank you

[VocalRemover.zip](https://github.com/Anjok07/ultimatevocalremovergui/files/5518284/VocalRemover.zip)

**Comment by ManOrMonster** [comment]
`SELECT ('E:/Creation/Original Songs/01 Abigail Blue.mp3',)
100%|██████████████████████████████████████████████████████████████████████████████████| 22/22 [00:01<00:00, 12.26it/s]`

That's all it shows. Then when it gets to "inverse stft of instruments and vocals", it locks up. After 30 seconds or so, it crashes.

**Comment by DilanBoskan** [comment]
Alright, I got mixed up with the Drag & Drop bug.

To Debug the issue, could you replace both spec_utils.py files in both lib_v2 and lib_v4 with these here and send the console output?
I will assign this issue to @Anjok07, he is a bit more knowledgable on the conversion process.

[lib_v2-spec_utils.zip](https://github.com/Anjok07/ultimatevocalremovergui/files/5518523/lib_v2-spec_utils.zip)
[lib_v4-spec_utils.zip](https://github.com/Anjok07/ultimatevocalremovergui/files/5518530/lib_v4-spec_utils.zip)

**Comment by ManOrMonster** [comment]
`SELECT ('E:/Creation/Original Songs/01 Abigail Blue.mp3',)
100%|██████████████████████████████████████████████████████████████████████████████████| 22/22 [00:01<00:00, 11.56it/s]`

`1
2
3`

**Comment by Anjok07** [comment]
@ManOrMonster - I tried replicating the error but everything seems to be working on my end. I'll have to dig into this a bit more. My advice would be for you to uninstall everything and start from scratch.

**Comment by Anjok07** [comment]
@ManOrMonster - Please open the application from the command prompt and paste the error output given when the application closes after that 30 seconds.

**Comment by ManOrMonster** [comment]
Same output, but it sits there with a blinking cursor long after the GUI closes, like it's still running.

**Comment by Anjok07** [comment]
@ManOrMonster The command prompt you opened the application doesn't show any errors?

**Comment by ManOrMonster** [comment]
Unfortunately, no.

**Comment by Anjok07** [comment]
@ManOrMonster - What is the name of the model you are using?

**Comment by ManOrMonster** [comment]
I've tried:

MGM-32000-512
MGM-44100-512
Multi-Genre Model

**Comment by DilanBoskan** [comment]
Could you try reinstalling the librosa library?
Could you send a video of the application hanging up, from start to finish, where boththe cmd and the application is viewable fully?

Thank you that would help tremendously

**Comment by ManOrMonster** [comment]
Reinstalled, same issue.

[video.zip](https://github.com/Anjok07/ultimatevocalremovergui/files/5527335/video.zip)

**Comment by Anjok07** [comment]
@ManOrMonster - I reviewed the video carefully and compared my Python packages with yours. I went ahead and updated the requirements.txt file with the exact same package versions I have installed on my machine.  

Please proceed with the following - 

1. Delete your current installation of Python as well as the current version of the UVR-GUI you have saved.
2. Follow the install instructions [here ](https://github.com/Anjok07/ultimatevocalremovergui/blob/beta/README.md )and make sure to download and use the latest version of the beta [here](https://github.com/Anjok07/ultimatevocalremovergui/archive/beta.zip).

Also, please rename the v4 models you have with the following. 

- Change **_'MGM-32000-512.pth'_** to **_'MGM-32000-512_sr44100_hl512_w512_nf2048.pth'_**
- Change **_'MGM-44100-512.pth'_** to **_'MGM-44100-512_sr44100_hl512_w512_nf2048.pth'_**
- Change **_'MGM-44100-1024.pth'_** to **_'MGM-44100-1024_sr44100_hl1024_w512_nf2048.pth'_**

If you don't run them with the proper parameters, you risk poor conversion quality.

**Comment by DilanBoskan** [comment]
I think there is not much else we can do

**Comment by ManOrMonster** [comment]
After doing all that, there was an improvement. It only crashes after 15 seconds now instead of over a minute.

Also, I get this error when it starts:

```
C:\Users\*****\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\audio.py:161: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
100%|██████████████████████████████████████████████████████████████████████████████████| 43/43 [00:02<00:00, 15.34it/s]
```

```
Package       Version
------------- ------------
audioread     2.1.9
cffi          1.14.3
decorator     4.4.2
future        0.18.2
joblib        0.17.0
librosa       0.7.2
llvmlite      0.31.0
numba         0.48.0
numpy         1.19.4
opencv-python 4.4.0.46
Pillow        8.0.1
pip           20.2.4
pycparser     2.20
resampy       0.2.2
scikit-learn  0.23.2
scipy         1.5.4
setuptools    39.0.1
six           1.15.0
SoundFile     0.10.3.post1
soundstretch  1.2
threadpoolctl 2.1.0
torch         1.6.0+cu101
torchvision   0.7.0+cu101
tqdm          4.45.0
```

**Comment by Anjok07** [comment]
@ManOrMonster That 'PySoundFile' error can be safely ignored. 

Regarding the main issue, there may be a system setting preventing you from completing the conversion process (it might even be your Anti-virus). My advice to you at this point would be to try a test install of the application on another PC, VM, or platform. 

We have been unable to replicate your issue on our end.

**Comment by ManOrMonster** [comment]
I'm working on a VM but struggling to get network access on it. It's Ubuntu, but I'm assuming this should work just fine on that, right?

Any reason you can think of why tsurumeso's would work but not this?

**Comment by Anjok07** [comment]
@ManOrMonster - It's unclear to me why that is. However, I can confirm was able to test this GUI on 2 separate PC's, both running Windows 10, and 2 VM's, one running Windows 10 & another running Ubuntu.

**Comment by Anjok07** [comment]
@ManOrMonster - I also want to mention that I only ran conversions within a VM to test all of the GUI options, except the one enabling GPU conversions.

**Comment by ManOrMonster** [comment]
I figured it out. I thought I had tried this at one point, but apparently not.

If I run Command Prompt as administrator and run it from there, it works.

And it's not like I'm trying to save the output in the root of C: or something. It's just a folder on my E: drive. I don't have a super locked down Windows install either. What do you think might cause that?

In any case, we have a solution. Thanks for the help.

**Comment by DilanBoskan** [comment]
Great!!
Hindsight is 20/20 but this should have been the first thing I should have thought  of..
