### ISSUE TITLE
Ultimate Vocal Remover wont start on Macbook Pro - Catalina

### ISSUE THREAD

**Issue by ArthurEschner** [Anjok07/ultimatevocalremovergui#888]
After installation (which takes a while but eventually seems to install fine) when I double-click the app to start it or right-ckick & open, nothing happens at all. Almost like I didn't do anything. I followed the instructions using the terminal commands. Any ideas what I did wrong?

**Comment by Anjok07** [comment]
@ArthurEschner Users not running Ventura and above have been reporting issues. Are you running a Mac with an M1/M2 or an Intel version?

**Comment by ArthurEschner** [comment]
Im using an Intel Mac running Catalina

**Comment by Anjok07** [comment]
Please follow these instructions:

1. Go to the Applications folder.
2. Right-click the Ultimate Vocal Remover app and go to "Show contents" 
3. Go to Contents->MacOS
4. Open "UVR" and a terminal window should popup
5. Provide the terminal output here.

A

**Comment by Anjok07** [comment]
@ArthurEschner 

Please follow these instructions:

1. Go to the Applications folder.
2. Right-click the Ultimate Vocal Remover app and go to "Show contents" 
3. Go to Contents->MacOS
4. Open "UVR" and a terminal window should popup
5. Provide the terminal output here.

**Comment by ArthurEschner** [comment]
Thanks so much, I'll try that & get back to you shortly

**Comment by ArthurEschner** [comment]
@Anjok07 Here is the output from terminal: /Applications/Ultimate\ Vocal\ Remover.app/Contents/MacOS/UVR ; exit;
[16698] Error loading Python lib '/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/Python': dlopen: dlopen(/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/Python, 10): Symbol not found: _preadv
  Referenced from: /Applications/Ultimate Vocal Remover.app/Contents/Frameworks/Python (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by Anjok07** [comment]
Thank you for providing this! I will look into a fix for this.

**Comment by ArthurEschner** [comment]
@Anjok07 Thank you for looking into it.

**Comment by Anjok07** [comment]
@ArthurEschner This issue should be resolved now. Please reinstall it via the following link - 

https://github.com/Anjok07/ultimatevocalremovergui/releases/download/v5.6/Ultimate_Vocal_Remover_v5_6_MacOS_x86_64.dmg

**Comment by ArthurEschner** [comment]
@Anjok07 Thanks for this. Unfortunately still wont start. Here is the output this time: The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "UVR.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/__init__.py", line 209, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/__init__.py", line 5, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/convert.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/notation.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/__init__.py", line 77, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/utils.py", line 5, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "scipy/__init__.py", line 171, in <module>
ImportError: The `scipy` install you are using seems to be broken, (extension modules cannot be imported), please try reinstalling.

**Comment by GlauberJoe** [comment]
I'm having exactly the same issue here, installed from the DMG and when I try to run it the app icon Pops up on Dock and disappears. Tried reinstalling 3 times but no luck, hope to see a solution if possible.

**Comment by Anjok07** [comment]
> I'm having exactly the same issue here, installed from the DMG and when I try to run it the app icon Pops up on Dock and disappears. Tried reinstalling 3 times but no luck, hope to see a solution if possible. 
> 

@GlauberJoe What version of Mac OS are you on?

**Comment by GlauberJoe** [comment]
I'm on 10.15.7 Catalina

**Comment by Anjok07** [comment]
@GlauberJoe @ArthurEschner Unfortunately, I can't downgrade some of the libraries without potentially breaking compatibility with MacOS 13+. Are you able to upgrade to Big Sur or Monterey?

**Comment by GlauberJoe** [comment]
Can't cause most Daws and Audio tools and apps I use are still not working 100% with the new OSX so I won't risk it yet.

**Comment by melonjack** [comment]
@ArthurEschner i've managed to launch latest UVR on my MacBookPro15mid2012 through manual install. Just keep in mind the moment about sklearn and if you occasionally stuck somewhere in between manual installation process, try "--no-deps" flag in "pip3 install.."

**Comment by leemajo** [comment]
im having the same issue using Big Sur can you please help?

**Comment by AlawiYNWA** [comment]
Same issue here 
Big Sur

**Comment by GlauberJoe** [comment]
> @ArthurEschner i've managed to launch latest UVR on my MacBookPro15mid2012 through manual install. Just keep in mind the moment about sklearn and if you occasionally stuck somewhere in between manual installation process, try "--no-deps" flag in "pip3 install.."

Would you be so kind to do a step by step on how to install it manually? I'm on the same machine, but running Catalina. I'd appreciate your help!

**Comment by jperiod53** [comment]
I'm having the same issue when I try to launch UVR on my Mid 2014 Macbook Retina i7 running Big SUR. I get the same results, brief flash of the icon then nothing.

**Comment by samiiliuski** [comment]
Would it be possible to make some older versions available? I had 5.6 version from September that worked on my Catalina but I then upgraded to latest 5.6 version and it doesn't work anymore. I know it is a free product and all and this might be too much to ask! Thank you anyway for al the work!

**Comment by onedouble93** [comment]
Same issue over here, installs but won't open. Unfortunately updating is a risky business so still chilling with mojave at the moment would love to use UVR but seems like if people can no longer run it with catalina then I don't have any hope? was there any legacy versions that ran on mojave like the previous versions that seemed to work fine on catalina?

**Comment by samiiliuski** [comment]
> Same issue over here, installs but won't open. Unfortunately updating is a risky business so still chilling with mojave at the moment would love to use UVR but seems like if people can no longer run it with catalina then I don't have any hope? was there any legacy versions that ran on mojave like the previous versions that seemed to work fine on catalina?

Yes actually version 5.6 from September worked on Mojave (I wrote wrong previously that I'm on Catalina but I'm actually on Mojave too). I guess it was 5.6.x.x something , I don't remember the numbers I only remember that it was from September

**Comment by GeoffLumley** [comment]
I have same issue. My terminal output is 
Last login: Wed Nov 29 15:44:32 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
iMac-Catalina:~ Geoff$ /Applications/Ultimate\ Vocal\ Remover.app/Contents/MacOS/UVR ; exit;
Traceback (most recent call last):
  File "scipy/__init__.py", line 166, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "scipy/_lib/_ccallback.py", line 1, in <module>
  File "_ccallback_c.pyx", line 210, in init scipy._lib._ccallback_c
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "ctypes/__init__.py", line 8, in <module>
ImportError: dlopen(/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/lib-dynload/_ctypes.cpython-311-darwin.so, 2): Symbol not found: __dyld_shared_cache_contains_path
  Referenced from: /Applications/Ultimate Vocal Remover.app/Contents/Frameworks/lib-dynload/_ctypes.cpython-311-darwin.so (which was built for Mac OS X 12.6)
  Expected in: /usr/lib/libSystem.B.dylib


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "UVR.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/__init__.py", line 209, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/__init__.py", line 5, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/convert.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/notation.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/__init__.py", line 77, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/utils.py", line 5, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "scipy/__init__.py", line 171, in <module>
ImportError: The `scipy` install you are using seems to be broken, (extension modules cannot be imported), please try reinstalling.
[3022] Failed to execute script 'UVR' due to unhandled exception: The `scipy` install you are using seems to be broken, (extension modules cannot be imported), please try reinstalling.
[3022] Traceback:
Traceback (most recent call last):
  File "scipy/__init__.py", line 166, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "scipy/_lib/_ccallback.py", line 1, in <module>
  File "_ccallback_c.pyx", line 210, in init scipy._lib._ccallback_c
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "ctypes/__init__.py", line 8, in <module>
ImportError: dlopen(/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/lib-dynload/_ctypes.cpython-311-darwin.so, 2): Symbol not found: __dyld_shared_cache_contains_path
  Referenced from: /Applications/Ultimate Vocal Remover.app/Contents/Frameworks/lib-dynload/_ctypes.cpython-311-darwin.so (which was built for Mac OS X 12.6)
  Expected in: /usr/lib/libSystem.B.dylib


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "UVR.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/__init__.py", line 209, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/__init__.py", line 5, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/convert.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/notation.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/__init__.py", line 77, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/utils.py", line 5, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "scipy/__init__.py", line 171, in <module>
ImportError: The `scipy` install you are using seems to be broken, (extension modules cannot be imported), please try reinstalling.

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by OneBrainStudent** [comment]
> @GlauberJoe @ArthurEschner Unfortunately, I can't downgrade some of the libraries without potentially breaking compatibility with MacOS 13+. Are you able to upgrade to Big Sur or Monterey?

I'm having the same issue. I'm using MacBook Pro Mid 15 on Big Sur with 2.2 GHz Quad-Core Intel Core i7.

Terminal output:


/Applications/Ultimate\ Vocal\ Remover.app/Contents/MacOS/UVR ; exit;
Traceback (most recent call last):
  File "UVR.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/__init__.py", line 209, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/__init__.py", line 5, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/convert.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/notation.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/__init__.py", line 78, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/files.py", line 11, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "pooch/__init__.py", line 19, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "pooch/processors.py", line 14, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "lzma.py", line 27, in <module>
ImportError: dlopen(/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/lib-dynload/_lzma.cpython-311-darwin.so, 2): Library not loaded: @rpath/liblzma.5.dylib
  Referenced from: /Applications/Ultimate Vocal Remover.app/Contents/Frameworks/lib-dynload/_lzma.cpython-311-darwin.so
  Reason: Incompatible library version: _lzma.cpython-311-darwin.so requires version 10.0.0 or later, but liblzma.5.dylib provides version 8.0.0
[43230] Failed to execute script 'UVR' due to unhandled exception: dlopen(/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/lib-dynload/_lzma.cpython-311-darwin.so, 2): Library not loaded: @rpath/liblzma.5.dylib
  Referenced from: /Applications/Ultimate Vocal Remover.app/Contents/Frameworks/lib-dynload/_lzma.cpython-311-darwin.so
  Reason: Incompatible library version: _lzma.cpython-311-darwin.so requires version 10.0.0 or later, but liblzma.5.dylib provides version 8.0.0
[43230] Traceback:
Traceback (most recent call last):
  File "UVR.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/__init__.py", line 209, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/__init__.py", line 5, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/convert.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/notation.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/__init__.py", line 78, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/files.py", line 11, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "pooch/__init__.py", line 19, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "pooch/processors.py", line 14, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "lzma.py", line 27, in <module>
ImportError: dlopen(/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/lib-dynload/_lzma.cpython-311-darwin.so, 2): Library not loaded: @rpath/liblzma.5.dylib
  Referenced from: /Applications/Ultimate Vocal Remover.app/Contents/Frameworks/lib-dynload/_lzma.cpython-311-darwin.so
  Reason: Incompatible library version: _lzma.cpython-311-darwin.so requires version 10.0.0 or later, but liblzma.5.dylib provides version 8.0.0

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]


Please take a look in it, thank you. I appreciate you working on this project.

**Comment by Zhao-Joe** [comment]
Same issue here, too~~
Big Sur 11.6
MacBook Pro（16 int，2019 ） 
2.3 GHz 8 cores Intel Core i9

**Comment by aleprogressive** [comment]
@Anjok07 hi! I'm having the same issue, however, I don't care about getting this new version to work on my outdated OS installation. I would like to go back to the latest working version for Catalina, but apparently I'm not finding links to earlier versions of UVR. I was using UVR just fine until I got a notice about an update. After executing the update, UVR never launched again. So, going back would be just great for me! Is there a way to download an earlier version? 

Thank you!

**Comment by cobalt107** [comment]
same issue, seems persistent

**Comment by cobalt107** [comment]
I have a solution for you guys that worked for me.

Download UVR 5.5 instead.

Go here: [https://github.com/Anjok07/ultimatevocalremovergui/releases](https://github.com/Anjok07/ultimatevocalremovergui/releases)

- Scroll down to v5.5
- Open "Assets" dropdown list (Do not click download link in main body - that will give you v5.6)
- Download file from Sept 29th 2023 _(Ultimate_Vocal_Remover_v5_5_MacOS_x86_64_9_29.dmg)_
- Once installed, do not update

If you are new to UVR, this [video](https://www.youtube.com/watch?v=ykOKwz3eRUQ) will give you the basics.

I am sure the developers will patch a fix for current release, but this is fine for now. (thanks devs!)

**Comment by sloofin** [comment]
Same, on Sonoma 14.5, MAcbook Pro M1 Max 64GB. Tried downloading 5.5 but the link goes to 5.6 still.
In terminal I get this output:

Traceback (most recent call last):
  File "UVR.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/__init__.py", line 209, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/convert.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/notation.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/__init__.py", line 77, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/utils.py", line 1878, in <module>
  File "numba/core/decorators.py", line 234, in wrapper
  File "numba/core/dispatcher.py", line 863, in enable_caching
  File "numba/core/caching.py", line 601, in __init__
  File "numba/core/caching.py", line 337, in __init__
RuntimeError: cannot cache function '__shear_dense': no locator available for file 'librosa/util/utils.py'
[76624] Failed to execute script 'UVR' due to unhandled exception: cannot cache function '__shear_dense': no locator available for file 'librosa/util/utils.py'
[76624] Traceback:
Traceback (most recent call last):
  File "UVR.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/__init__.py", line 209, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/convert.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/notation.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/__init__.py", line 77, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/utils.py", line 1878, in <module>
  File "numba/core/decorators.py", line 234, in wrapper
  File "numba/core/dispatcher.py", line 863, in enable_caching
  File "numba/core/caching.py", line 601, in __init__
  File "numba/core/caching.py", line 337, in __init__
RuntimeError: cannot cache function '__shear_dense': no locator available for file 'librosa/util/utils.py'

**Comment by guxijapan** [comment]
just fit model for catalina(v5.5)
[アルティメット_ボーカル_リムーバー_v5_5_MacOS_x86_64_9_29.dmg](https://github.com/Anjok07/ultimatevocalremovergui/releases/download/v5.5.0/Ultimate_Vocal_Remover_v5_5_MacOS_x86_64_9_29.dmg)
